apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-redis-cluster
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http-metrics
      interval: 15s
