apiVersion: cache.example.com/v1
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: default
spec:
  masters: 3
  replicasPerMaster: 1
  redisVersion: "7.2"
  autoScaleEnabled: true
  cpuThreshold: 12